on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@master

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.HANDSON201112TOSAT}}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSID }}
        resourceGroupName: ${{ secrets.RG }}
        template: Hands-on-Lab/templates/deploy-vm-as-domain-member.json
        parameters: Hands-on-Lab/templates/tosatvmparameters.json
        
      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
