name: TEST Deploy 0217
on: 
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: Resource Group Name
        required: true
        
        jobs:
  deploy-virtual-machine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, ${{ github.event.inputs.resourceGroupName }}
